### ISSUE TITLE
Attempting to open previous version of sets leads to an error message.

### ISSUE THREAD

**Issue by Circeus** [mzabsky/webdrafter#5]
As of right now, it seems impossible to look at previous versions of set without getting this error message:

> Additional information:
> Zend\Mvc\Router\Exception\InvalidArgumentException
> 
> File:
> 
> ```
> /web/htdocs3/planesculptorsnet/home/vendor/ZF2/library/Zend/Mvc/Router/Http/Segment.php:298
> ```
> 
> Message:
> 
> ```
> Missing parameter "set_version_id"
> ```

**Comment by mzabsky** [comment]
Fixed, thanks for reporting.
